MountainCoders/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    # path('post/', include('post.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.blog, name='blog'),
    path('blogpost/<str:slug>', views.blogpost, name='blogpost'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    # path('login/', views.login, name='login'),
    # path('logout/', views.logout, name='logout'),
    # path('signup/', views.signup, name='signup'),
    path('search/', views.search, name='search'),
]

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    sno = models.AutoField(primary_key=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    short_desc = models.CharField(max_length=500, default="")
    author = models.CharField(max_length=50, default="")
    slug = models.SlugField(max_length=200)
    time = models.DateField(auto_now_add=True)
    thumbnail = models.ImageField(upload_to="blog/images")

    def __str__(self):
        return self.title

class Contact(models.Model):
    sno = models.AutoField(primary_key=True)
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=50)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    desc = models.TextField()
    time = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.fname
    

blog/views.py
from django.shortcuts import render, HttpResponse,  redirect
from blog.models import Blog, Contact
from django.contrib import messages
import math
# from django.contrib.auth import authenticate, login, logout
# from django.contrib.auth.models import User
# Create your views here.
def home(request):
    return render(request, "index.html")

def blog(request):
    no_of_posts = 3
    # if request.GET['pageno']
    page = request.GET.get('page')
    if page is None:
        page = 1
    else:
        page = int(page)
    '''
    1 :0 -5
    2 :5 -10
    3 :10 -15
    4 :15 -20

    1: 0 - 0 + no_of_posts
    2: no_of_posts to no_of posts + no_of_posts
    3: no_of_posts + no_of_posts to no_of_posts + no_of_posts + no_of_posts

    (page_no-1) to page_no*no_of_posts

    '''
    blogs = Blog.objects.all()
    length = len(blogs)
    blogs = Blog.objects.all()[(page-1)*no_of_posts: page*no_of_posts]
    if page>1:
        prev = page - 1
    else:
        prev = None
    if page<math.ceil(length/no_of_posts):
        nxt = page + 1
    else:
        nxt = None
    context = {'blogs': blogs, 'prev': prev, 'nxt': nxt}
    return render(request, "bloghome.html", context)

def blogpost(request, slug):
    blog = Blog.objects.filter(slug=slug).first()
    context = {'blog':blog}
    return render(request, "blogpost.html", context)

def contact(request):
    if request.method == 'POST':
        fname = request.POST.get("fname")
        lname = request.POST.get("lname")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        city = request.POST.get("city")
        state= request.POST.get("state")
        desc = request.POST.get("desc")
        # instance = Contact(fname=fname, lname=lname, email=email, phone=phone, city=city, state=state, desc=desc)
        # instance.save()

        if len(fname)<2 or len(email)<4 or len(phone)<10 or len(desc)<4:
            messages.error(request, "Please fill the details correctely")
        else:
            instance = Contact(fname=fname, lname=lname, email=email, phone=phone, city=city, state=state, desc=desc)
            instance.save()
            messages.success(request, "Your form has been sent successfully")


    return render(request, "contact.html")

def about(request):
    return render(request, "about.html")


def search(request):
    query = request.GET['query']
    if len(query)>90:
        blogs = Blog.objects.none()
    else:
        blogsTitle = Blog.objects.filter(title__icontains=query)
        blogsContent = Blog.objects.filter(content__icontains=query)
        blogs = blogsTitle.union(blogsContent)
        
    if blogs.count() == 0:
        []
    params = {'blogs':blogs, 'query': query}
    return render(request, 'search.html', params)

    # return render(request, "search.html")

# def login(request):
#     return render(request, 'index.html' )

# def logout(request):
#     return render(request, 'index.html' )

# def signup(request):
#     return render(request, 'index.html' )


    

blog/templates/about.html
{% extends 'base.html' %}
{% block tag %}
<meta name="description" content=" ">
{% endblock tag %}
{% block title %} About {% endblock title %}
{% block css %}
<style>
  .container{
    min-height: 100vh;
  }
</style>
{% endblock css %}
{% block aboutactive %} active {% endblock aboutactive %}
{% block body %}


      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8 blog-main">
            <h3 class="pb-4 mb-4 font-italic border-bottom">
              About Us
            </h3>
      
            <div class="blog-post">
              <h2 class="blog-post-title">We are a coding comunity that providing you programming blog , tutorial and more.</h2>

      
              <p>Our goal is to let programmers keep on improving their coding skills by solving the World's most challenging problems, learn new concepts, and get inspired by the best developers..</p>
              <hr>
             
            
            </div><!-- /.blog-post -->
      
      
      
      
          </div><!-- /.blog-main -->
      
          <aside class="col-md-4 blog-sidebar">
            <div class="p-4 mb-3 bg-light rounded">
              <h4 class="font-italic">About</h4>
              <p class="mb-0">Our goal is to let programmers keep on improving their coding skills by solving the World's most challenging problems, learn new concepts, and get inspired by the best developers.. </p>
            </div>
      
            <div class="p-4">
              <h4 class="font-italic">What we are providing you?</h4>
              <ol class="list-unstyled mb-0">
                <li><a href="#">Present a lightning talk.</a></li>
                <li><a href="#">Deliver a training course.</a></li>
                <li><a href="#">Present at a local user group.</a></li>
                <li><a href="#">Present a lightning talk.</a></li>
                <li><a href="#">Present at a conference.</a></li>
                <li><a href="#">Publish a tutorial</a></li>
                <li><a href="#">Publish a constructive code review of an open source project</a></li>
                <li><a href="#">AWrite a programming book</a></li>
                
              </ol>
            </div>
      

      
        </div><!-- /.row -->
      
      </main>
    {% endblock body %}
    

blog/templates/base.html
<!doctype html>
<html lang="en">
  
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block tag %}
  {% endblock tag %}
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="icon" type="image/png" href="/static/img/favicon.png">
  {% block css %}
  
  {% endblock css %}
  
  <title> {% block title %} {% endblock title %}</title>
</head>

<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <img src="/static/img/logo.png" alt="logo" class="img-thumbnail rounded-circle p-0" width="46px">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse mx-1" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto text-center">
        <li class="nav-item {% block homeactive %}{% endblock homeactive %}">
          <a class="nav-link " href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item{% block blogactive %}{% endblock blogactive %}">
          <a class="nav-link" href="/blog">Blog</a>
        </li>
        <li class="nav-item {% block aboutactive %}{% endblock aboutactive %}">
          <a class="nav-link" href="/about">About</a>
        </li>
        
        <li class="nav-item {% block contactactive %}{% endblock contactactive %}">
          <a class="nav-link" href="/contact">Contact Us</a>
        </li>
       
      </ul>
      <form action="/search/" method="get" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name="query" id="query" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
      </form>

     
    </div>
  </nav>
  
  {% for message in messages %}

  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <strong>Message</strong> {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
      {% endfor %}
      
     


{% block body %}
{% endblock body %}

<!-- footer start here -->
<footer class="container-fluid py-5 bg-dark text-light">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"></circle><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"></path></svg>
      <small class="d-block mb-3 text-muted text-light">© 2020-2021</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Business</a></li>
        <li><a class="text-muted" href="#">Education</a></li>
        <li><a class="text-muted" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>

  <div class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">© 2017-2020 All rights riserved</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
      <li class="list-item my-4"><a href="#">Back to top</a></li>
    </ul>
  </div>
</footer>


 

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
</body>

</html>

blog/templates/bloghome.html
{% extends 'base.html' %}
{% block tag %}
<meta name="description" content=" ">
{% endblock tag %}
{% block title %} Blog {% endblock title %}
{% block blogactive %} active {% endblock blogactive %}
{% block css %}
<style>
  .container {
    min-height: 100vh;
  }
</style>
{% endblock css %}
{% block body %}
<div class="container">
  <h1 class="my-4">Welcome to Mountain coders blog</h1>

  {% for blog in blogs %}

  <div class="media">
    <div class="media-body">
      <img src="/media/{{blog.thumbnail}}" class="img-fluid img-thumbnail" width="222px" alt="...">
      <h5 class="mt-0 "> <a class="text-dark" href="/blogpost/{{blog.slug}}"> {{blog.title}}</h5></a>

      <p>{{blog.short_desc}}...</p>
      <a href="/blogpost/{{blog.slug}}"><button class="btn btn-primary mb-3"> Read more</button></a>
      <hr>
    </div>
  </div>

  {% endfor %}
  <div class="mb-2">
{% if prev %}
    <button class="btn btn-info"> <a class="text-light" href="/blog?page={{prev}}"> &laquo; Previews </a></button>
{% else %}
<button class="btn btn-info"> <a class="text-light" href="#"> &laquo; Previews </a></button>
{% endif %}

{% if nxt %}
    <button class="btn btn-info float-right"> <a class="text-light" href="/blog?page={{nxt}}"> Next &raquo; </a></button>
{% else %}
<button class="btn btn-info float-right"> <a class="text-light" href="#"> Next &raquo; </a></button>
{% endif %}
  </div>

</div>

{% endblock body %}

blog/templates/blogpost.html
{% extends 'base.html' %}
{% block tag %}
<meta name="description" content=" ">
{% endblock tag %}
{% block title %} Blog Posts {% endblock title %}
{% block blogactive %} active {% endblock blogactive %}
{% block css %}
<style>
  .container{
    min-height: 100vh;
  }
</style>
{% endblock css %}
{% block body %}


<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-4 mb-4 font-italic border-bottom">
        Welcome 
      </h3>

    

      <div class="blog-post">
        <h2 class="blog-post-title">{{blog.title}}</h2>
        <p class="blog-post-meta"> {{blog.time}} By <a href="#"> {{blog.author}}</a></p>

      <div class="container my-4">
        {{blog.content|safe}}
      </div>
      </div><!-- /.blog-post -->

      

    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">
      <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">Description</h4>
        <p class="mb-0">{{blog.short_desc}}</p>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2014</a></li>
          <li><a href="#">February 2014</a></li>
          <li><a href="#">January 2014</a></li>
          <li><a href="#">December 2013</a></li>
          <li><a href="#">November 2013</a></li>
          <li><a href="#">October 2013</a></li>
          <li><a href="#">September 2013</a></li>
          <li><a href="#">August 2013</a></li>
          <li><a href="#">July 2013</a></li>
          <li><a href="#">June 2013</a></li>
          <li><a href="#">May 2013</a></li>
          <li><a href="#">April 2013</a></li>
        </ol>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</main>


{% endblock body %}






    

blog/templates/contact.html
{% extends 'base.html' %}
{% block tag %}
<meta name="description" content=" ">
{% endblock tag %}
{% block title %} Contacts {% endblock title %}
{% block css %}
<style>

@import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');
*{
  margin: 0;
  padding: 0;
  font-family: 'Poppins', sans-serif;
}
.container{
    min-height: 100vh;
}

</style>
{% endblock css %}
{% block contactactive %} active {% endblock contactactive %}
{% block body %}


<div class="container">
<h1 class="my-4 text-center">Contact Us</h1>

<form class="needs-validation" method="post" action="/contact/" novalidate>
    {% csrf_token %}

    <div class="form-row">
      <div class="col-md-6 mb-3">
        <label for="validationCustom01">First name</label>
        <input type="text" class="form-control" id="fname" name="fname" required>
        <div class="valid-feedback">
          Looks good!
        </div>
      </div>
      <div class="col-md-6 mb-3">
        <label for="validationCustom02">Last name</label>
        <input type="text" class="form-control" id="lname" name="lname" required>
        <div class="valid-feedback">
          Looks good!
        </div>
      </div>

        <div class="col-md-6 mb-3">
          <label for="email">Email</label>
          <input type="email" class="form-control" id="email" name="email"  required>
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-md-6 mb-3">
          <label for="validationCustom02">Mobile Number</label>
          <input type="tel" class="form-control" id="phone" name="phone"  required>
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>


    </div>
    <div class="form-row">
      <div class="col-md-6 mb-3">
        <label for="validationCustom03">City</label>
        <input type="text" class="form-control" id="city" name="city" required>
        <div class="invalid-feedback">
          Please provide a valid city.
        </div>
      </div>
      <div class="col-md-6 mb-3">
        <label for="validationCustom04">State</label>
        <input type="text" class="form-control" id="state" name="state" required>
        </select>
        <div class="invalid-feedback">
          Please select a valid state.
        </div>
      </div>
     

    </div>


    <div class="form-group">
        <label for="exampleFormControlTextarea1">Elaborate Your Concern</label>
        <textarea class="form-control" id="desc" name="desc" rows="5"></textarea>
      </div>

    <div class="form-group">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
        <label class="form-check-label" for="invalidCheck">
          Agree to terms and conditions
        </label>
        <div class="invalid-feedback">
          You must agree before submitting.
        </div>
      </div>
    </div>
    <button class="btn btn-primary my-4" type="submit">Submit form</button>
  </form>
  
  <script>
  // Example starter JavaScript for disabling form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
  </script>



 





</div>
{% endblock body %}

blog/templates/search.html
{% extends 'base.html' %}
{% block title %} Search Results for  {% endblock title %}
{% block css %}
<style>
 .container{
     min-height: 80vh;
 }
</style>
{% endblock %}
{% block body %} 

<div class="container my-2">
    <h3>Search Results</h3>
    {% if blogs|length < 1 %}
  
   <p> Your search - <b>{{query|slice:"0:444"}}</b> - did not match any documents.</p>
  
   <p class="mb-2">Suggestions:</p> 
    
    <li> Make sure that all words are spelled correctly.</li>
    <li> Try different keywords.</li>
    <li> Try more general keywords.</li>
  
    {% endif %}
    {% for post in blogs %} 
        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 my-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-dark">Posted By {{post.author}}</strong>
            <h3 class="mb-0">{{post.title}}</h3>
            <!-- <div class="mb-1 text-muted">{{post.timeStamp}}</div> -->
            <p class="card-text mb-auto">{{post.short_desc}}</p>
  
            <div class="my-2">
                <a href="/blog/{{blog.slug}}" role="button" class="btn btn-primary">Continue reading</a>
            </div>
          </div>
         
        </div>
        {% endfor post in blogs %}
  </div>
  
  
 

{% endblock body %}

blog/templates/tiny.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://cdn.tiny.cloud/1/crgi5v6wte5lpov5iebof876pz3u7ycwrzww1j8mwxwmed2a/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>

    <script>
        tinymce.init({
            selector: '#id_content',
            plugins: 'print preview powerpaste casechange importcss tinydrive searchreplace autolink autosave save directionality advcode visualblocks visualchars fullscreen image link media mediaembed template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists checklist wordcount tinymcespellchecker a11ychecker imagetools textpattern noneditable help formatpainter permanentpen pageembed charmap tinycomments mentions quickbars linkchecker emoticons advtable',
            tinydrive_token_provider: 'URL_TO_YOUR_TOKEN_PROVIDER',
            tinydrive_dropbox_app_key: 'YOUR_DROPBOX_APP_KEY',
            tinydrive_google_drive_key: 'YOUR_GOOGLE_DRIVE_KEY',
            tinydrive_google_drive_client_id: 'YOUR_GOOGLE_DRIVE_CLIENT_ID',
            mobile: {
                plugins: 'print preview powerpaste casechange importcss tinydrive searchreplace autolink autosave save directionality advcode visualblocks visualchars fullscreen image link media mediaembed template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists checklist wordcount tinymcespellchecker a11ychecker textpattern noneditable help formatpainter pageembed charmap mentions quickbars linkchecker emoticons advtable'
            },
            menu: {
                tc: {
                    title: 'TinyComments',
                    items: 'addcomment showcomments deleteallconversations'
                }
            },
            menubar: 'file edit view insert format tools table tc help',
            toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | a11ycheck ltr rtl | showcomments addcomment',
            autosave_ask_before_unload: true,
            autosave_interval: '30s',
            autosave_prefix: '{path}{query}-{id}-',
            autosave_restore_when_empty: false,
            autosave_retention: '2m',
            image_advtab: true,
            link_list: [
                { title: 'My page 1', value: 'http://www.tinymce.com' },
                { title: 'My page 2', value: 'http://www.moxiecode.com' }
            ],
            image_list: [
                { title: 'My page 1', value: 'http://www.tinymce.com' },
                { title: 'My page 2', value: 'http://www.moxiecode.com' }
            ],
            image_class_list: [
                { title: 'None', value: '' },
                { title: 'Some class', value: 'class-name' }
            ],
            importcss_append: true,
            templates: [
                { title: 'New Table', description: 'creates a new table', content: '<div class="mceTmpl"><table width="98%%"  border="0" cellspacing="0" cellpadding="0"><tr><th scope="col"> </th><th scope="col"> </th></tr><tr><td> </td><td> </td></tr></table></div>' },
                { title: 'Starting my story', description: 'A cure for writers block', content: 'Once upon a time...' },
                { title: 'New list with dates', description: 'New List with dates', content: '<div class="mceTmpl"><span class="cdate">cdate</span><br /><span class="mdate">mdate</span><h2>My List</h2><ul><li></li><li></li></ul></div>' }
            ],
            template_cdate_format: '[Date Created (CDATE): %m/%d/%Y : %H:%M:%S]',
            template_mdate_format: '[Date Modified (MDATE): %m/%d/%Y : %H:%M:%S]',
            height: 600,
            image_caption: true,
            quickbars_selection_toolbar: 'bold italic | quicklink h2 h3 blockquote quickimage quicktable',
            noneditable_noneditable_class: 'mceNonEditable',
            toolbar_mode: 'sliding',
            spellchecker_whitelist: ['Ephox', 'Moxiecode'],
            tinycomments_mode: 'embedded',
            content_style: '.mymention{ color: gray; }',
            contextmenu: 'link image imagetools table configurepermanentpen',
            a11y_advanced_options: true,
            /*
            The following settings require more configuration than shown here.
            For information on configuring the mentions plugin, see:
            https://www.tiny.cloud/docs/plugins/mentions/.
            */
            mentions_selector: '.mymention',
            mentions_fetch: mentions_fetch,
            mentions_menu_hover: mentions_menu_hover,
            mentions_menu_complete: mentions_menu_complete,
            mentions_select: mentions_select

        });
    </script>

</head>

<body>
    <h1>TinyMCE Quick Start Guide</h1>
    <form method="post">
        <textarea id="id_content">Hello, World!</textarea>
    </form>
</body>

</html>